apiVersion: v1
kind: Service
metadata:
  name: hms-service
  namespace: hms-ns
spec:
  selector:
    app: hms-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer